export const API_URL = 'https://norma.nomoreparties.space/api/';

export const INGREDIENT = 'ingredient';
export const CONSTRUCTOR = 'constructor';

export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const RESET_CURRENT_INGREDIENT = 'RESET_CURRENT_INGREDIENT';
export const SET_INGREDIENTS_CURRENT_TAB = 'SET_INGREDIENTS_CURRENT_TAB';
export const INCREMENT_INGREDIENT_COUNTER = 'INCREMENT_INGREDIENT_COUNTER';
export const DECREMENT_INGREDIENT_COUNTER = 'DECREMENT_INGREDIENT_COUNTER';

export const SET_CONSTRUCTOR_BUN = 'SET_CONSTRUCTOR_BUN';
export const ADD_CONSTRUCTOR_ITEM = 'ADD_CONSTRUCTOR_ITEM';
export const REMOVE_CONSTRUCTOR_ITEM = 'REMOVE_CONSTRUCTOR_ITEM';
export const MOVE_CONSTRUCTOR_ITEM = 'MOVE_CONSTRUCTOR_ITEM';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';

export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const HIDE_ORDER = 'HIDE_ORDER';

export const SEND_REGISTRATION_REQUEST = 'SEND_REGISTRATION_REQUEST';
export const SEND_REGISTRATION_FAILED = 'SEND_REGISTRATION_FAILED';
export const SEND_REGISTRATION_SUCCESS = 'SEND_REGISTRATION_SUCCESS';

export const SEND_LOGIN_REQUEST = 'SEND_LOGIN_REQUEST';
export const SEND_LOGIN_FAILED = 'SEND_LOGIN_FAILED';
export const SEND_LOGIN_SUCCESS = 'SEND_LOGIN_SUCCESS';

export const SEND_LOGOUT_REQUEST = 'SEND_LOGOUT_REQUEST';
export const SEND_LOGOUT_FAILED = 'SEND_LOGOUT_FAILED';
export const SEND_LOGOUT_SUCCESS = 'SEND_LOGOUT_SUCCESS';

export const SEND_FORGOT_PASSWORD_REQUEST = 'SEND_FORGOT_PASSWORD_REQUEST';
export const SEND_FORGOT_PASSWORD_FAILED = 'SEND_FORGOT_PASSWORD_FAILED';
export const SEND_FORGOT_PASSWORD_SUCCESS = 'SEND_FORGOT_PASSWORD_SUCCESS';

export const SEND_RESET_PASSWORD_REQUEST = 'SEND_RESET_PASSWORD_REQUEST';
export const SEND_RESET_PASSWORD_FAILED = 'SEND_RESET_PASSWORD_FAILED';
export const SEND_RESET_PASSWORD_SUCCESS = 'SEND_RESET_PASSWORD_SUCCESS';

export const SEND_GET_PROFILE_REQUEST = 'SEND_GET_PROFILE_REQUEST';
export const SEND_GET_PROFILE_FAILED = 'SEND_GET_PROFILE_FAILED';
export const SEND_GET_PROFILE_SUCCESS = 'SEND_GET_PROFILE_SUCCESS';

export const SEND_SAVE_PROFILE_REQUEST = 'SEND_SAVE_PROFILE_REQUEST';
export const SEND_SAVE_PROFILE_FAILED = 'SEND_SAVE_PROFILE_FAILED';
export const SEND_SAVE_PROFILE_SUCCESS = 'SEND_SAVE_PROFILE_SUCCESS';

export const SEND_TOKEN_REFRESH_REQUEST = 'SEND_TOKEN_REFRESH_REQUEST';
export const SEND_TOKEN_REFRESH_FAILED = 'SEND_TOKEN_REFRESH_FAILED';
export const SEND_TOKEN_REFRESH_SUCCESS = 'SEND_TOKEN_REFRESH_SUCCESS';
