export const SEND_REGISTRATION_REQUEST: 'SEND_REGISTRATION_REQUEST' = 'SEND_REGISTRATION_REQUEST';
export const SEND_REGISTRATION_FAILED: 'SEND_REGISTRATION_FAILED' = 'SEND_REGISTRATION_FAILED';
export const SEND_REGISTRATION_SUCCESS: 'SEND_REGISTRATION_SUCCESS' = 'SEND_REGISTRATION_SUCCESS';

export const SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST' = 'SEND_LOGIN_REQUEST';
export const SEND_LOGIN_FAILED: 'SEND_LOGIN_FAILED' = 'SEND_LOGIN_FAILED';
export const SEND_LOGIN_SUCCESS: 'SEND_LOGIN_SUCCESS' = 'SEND_LOGIN_SUCCESS';

export const SEND_LOGOUT_REQUEST: 'SEND_LOGOUT_REQUEST' = 'SEND_LOGOUT_REQUEST';
export const SEND_LOGOUT_FAILED: 'SEND_LOGOUT_FAILED' = 'SEND_LOGOUT_FAILED';
export const SEND_LOGOUT_SUCCESS: 'SEND_LOGOUT_SUCCESS' = 'SEND_LOGOUT_SUCCESS';

export const SEND_FORGOT_PASSWORD_REQUEST: 'SEND_FORGOT_PASSWORD_REQUEST' = 'SEND_FORGOT_PASSWORD_REQUEST';
export const SEND_FORGOT_PASSWORD_FAILED: 'SEND_FORGOT_PASSWORD_FAILED' = 'SEND_FORGOT_PASSWORD_FAILED';
export const SEND_FORGOT_PASSWORD_SUCCESS: 'SEND_FORGOT_PASSWORD_SUCCESS' = 'SEND_FORGOT_PASSWORD_SUCCESS';

export const SEND_RESET_PASSWORD_REQUEST: 'SEND_RESET_PASSWORD_REQUEST' = 'SEND_RESET_PASSWORD_REQUEST';
export const SEND_RESET_PASSWORD_FAILED: 'SEND_RESET_PASSWORD_FAILED' = 'SEND_RESET_PASSWORD_FAILED';
export const SEND_RESET_PASSWORD_SUCCESS: 'SEND_RESET_PASSWORD_SUCCESS' = 'SEND_RESET_PASSWORD_SUCCESS';

export const SEND_GET_PROFILE_REQUEST: 'SEND_GET_PROFILE_REQUEST' = 'SEND_GET_PROFILE_REQUEST';
export const SEND_GET_PROFILE_FAILED: 'SEND_GET_PROFILE_FAILED' = 'SEND_GET_PROFILE_FAILED';
export const SEND_GET_PROFILE_SUCCESS: 'SEND_GET_PROFILE_SUCCESS' = 'SEND_GET_PROFILE_SUCCESS';

export const SEND_SAVE_PROFILE_REQUEST: 'SEND_SAVE_PROFILE_REQUEST' = 'SEND_SAVE_PROFILE_REQUEST';
export const SEND_SAVE_PROFILE_FAILED: 'SEND_SAVE_PROFILE_FAILED' = 'SEND_SAVE_PROFILE_FAILED';
export const SEND_SAVE_PROFILE_SUCCESS: 'SEND_SAVE_PROFILE_SUCCESS' = 'SEND_SAVE_PROFILE_SUCCESS';

export const SEND_TOKEN_REFRESH_REQUEST: 'SEND_TOKEN_REFRESH_REQUEST' = 'SEND_TOKEN_REFRESH_REQUEST';
export const SEND_TOKEN_REFRESH_FAILED: 'SEND_TOKEN_REFRESH_FAILED' = 'SEND_TOKEN_REFRESH_FAILED';
export const SEND_TOKEN_REFRESH_SUCCESS: 'SEND_TOKEN_REFRESH_SUCCESS' = 'SEND_TOKEN_REFRESH_SUCCESS';

