export const SET_CONSTRUCTOR_BUN: 'SET_CONSTRUCTOR_BUN' = 'SET_CONSTRUCTOR_BUN';
export const ADD_CONSTRUCTOR_ITEM: 'ADD_CONSTRUCTOR_ITEM' = 'ADD_CONSTRUCTOR_ITEM';
export const REMOVE_CONSTRUCTOR_ITEM: 'REMOVE_CONSTRUCTOR_ITEM' = 'REMOVE_CONSTRUCTOR_ITEM';
export const MOVE_CONSTRUCTOR_ITEM: 'MOVE_CONSTRUCTOR_ITEM' = 'MOVE_CONSTRUCTOR_ITEM';

export const RESET_CONSTRUCTOR: 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';
